using System;
using System.Collections.Generic;

namespace PG.StarWarsGame.Engine;

public static class HardcodedEngineAssets
{
    /// <summary>
    /// These models / particles are hardcoded into StarWarsG.exe.
    /// </summary>
    public static IList<string> HardcodedFocModelsParticles { get; } = new List<string>
    {
        "i_tutorial_arrow.alo",
        "p_hero_empire_fx.alo",
        "i_tactical_corrupt.alo",
        "p_icon_corrupt.alo",
        "w_planet_select_neutral.alo",
        "i_game_arrow.alo",
        "i_galactic_radar.alo",
        "W_TextScroll.alo"
    };


    /// <summary>
    /// These models / particles are hardcoded into StarWarsG.exe.
    /// </summary>
    public static IList<string> HardcodedEawModelsParticles { get; } = new List<string>
    {
        "i_tutorial_arrow.alo",
        "p_hero_empire_fx.alo",
        "w_planet_select_neutral.alo",
        "i_game_arrow.alo",
        "i_galactic_radar.alo",
        "W_TextScroll.alo"
    };

    public static IList<string> HardcodedFocTextures { get; } = new List<string>
    {
        "splash.tga",
        "SPLASH_E3.tga",
        "i_button_temporary.tga",
        "i_attention00.tga",
        "i_tree_arrow_right.tga",
        "load_overlay.tga",
        "i_pa_weather_sun.tga",
        "i_pa_weather_fire.tga",
        "i_pa_weather_snow.tga",
        "i_pa_weather_rain.tga",
        "i_pa_weather_wind.tga",
        "Menuback_Overlay.TGA",
        "i_button_space_station.tga",
        "i_button_ground_base.tga",
        "i_button_space_unitcount.tga",
        "i_button_ground_unitcount.tga",
        "i_dialogue_blank.tga",
        "checked_box.tga",
        "Galactic_Back.tga",
        "Generic_Space.tga",
        "Generic_Land.tga",
        "red_dot.tga",
        "yellow_dot.tga",
        "green_dot.tga",
        "i_tree_arrow_2right.tga",
        "i_tree_arrow_3right.tga",
        "i_tree_arrow_down.tga",
        "Generic_Flat_B.tga",
        "w_generic_white.tga",
        "w_shadow_blob.tga",
        "w_light_blob.tga",
        "p_particle_master.tga",
        "missing_texture_xxx.tga",
        "D_master_decal.tga",
        "p_particle_depth_master.tga",
        "MT_CommandBar.tga",
        "MT_CommandBarCompressed.dds",
        "DEFAULTPOINTER_00.TGA",
        "tractor_beam00.tga",
        "i_button_unknown.tga",
        "i_icon_stealth.tga",
        "e_line2.tga",
        "e_line.tga",
        "i_bar_icons_space.tga",
        "i_bar_icons_land.tga",
        "e_topbar2.tga",
        "e_topbar.tga",
        "e_against_frame.tga",
        "missing.tga",
        "i_encyclopedia_border.tga",
        "i_radar_default_blip.tga",
        "select_overlay.tga",
        "i_icon_raid.tga",
        "maptemp.tga",
        "shield_range.tga",
        "W_galaxy_line.tga",
        "W_galaxy_line_alpha.tga",
        "W_galaxy_dot.tga",
        "i_sa_defend_mode.tga",
        "i_sa_deploy.tga",
        "i_sa_interdict.tga",
        "i_sa_barrage_area.tga",
        "i_sa_capture_vehicles.tga",
        "i_sa_spread_out.tga",
        "i_sa_power_to_engines.tga",
        "i_sa_rocket_attack.tga",
        "i_sa_power_to_weapons.tga",
        "i_sa_tractor_beam.tga",
        "i_sa_fire_energy_weapon.tga",
        "i_sa_missile_jammer.tga",
        "i_sa_evasive_maneuvers.tga",
        "i_sa_all_ships_concentrate_fire.tga",
        "i_sa_sprint.tga",
        "i_sa_stim_pack.tga",
        "i_sa_s_foil_mode.tga",
        "i_sa_maximum_firepower.tga",
        "i_sa_swap_weapons.tga",
        "i_sa_full_salvo.tga",
        "i_sa_force_cloak.tga",
        "i_sa_sensor_jamming.tga",
        "i_sa_force_crush.tga",
        "i_sa_force_push.tga",
        "i_sa_force_lighting.tga",
        "i_sa_flame_thrower.tga",
        "i_sa_jetpack_jump.tga",
        "i_sa_force_protect.tga",
        "i_sa_hack_turret.tga",
        "i_sa_repair_vehicle.tga",
        "i_sa_sticky_bomb.tga",
        "i_sa_electronic_scramble.tga",
        "i_sa_area_heal.tga",
        "i_sa_join_me.tga",
        "i_sa_tow_cable_attack.tga",
        "i_sa_sensor_ping.tga",
        "i_sa_cover_me.tga",
        "i_sa_Harmonic_bomb.tga",
        "i_sa_drop_bomb.tga",
        "i_sa_weaken_enemy.tga",
        "i_sa_drain_life.tga",
        "i_sa_blast.tga",
        "i_sa_shield_flare.tga",
        "i_sa_deploy_squad.tga",
        "i_sa_stun.tga",
        "i_sa_contaminate.tga",
        "i_sa_berserker.tga",
        "i_sa_force_sight.tga",
        "i_sa_saber_throw.tga",
        "i_sa_laser_defense.tga",
        "i_sa_force_confuse.tga",
        "i_sa_leech_shields.tga",
        "i_sa_tactical_bribe.tga",
        "i_sa_cluster_bomb.tga",
        "i_sa_place_remote_bomb.tga",
        "i_sa_detonate_remote_bomb.tga",
        "i_sa_infection.tga",
        "i_sa_proximity_mines.tga",
        "i_sa_buzz_droids.tga",
        "i_sa_summon.tga",
        "i_sa_corrupt_systems.tga",
        "i_sa_hunt.tga",
        "i_sa_lure.tga",
        "i_sa_self_destruct.tga",
        "i_sa_deploy_stormtroopers.tga",
        "i_sa_ion_cannon_shot.tga",
        "i_sa_lucky_shot.tga",
        "lightning_default.tga",
        "Mon_Mothma.tga",
        "Tarkin.tga",
        "W_Cable.tga",
        "i_information00.tga",
        "W_Laser_Pill.tga",
        "lensflare.tga",
        "W_Space_FOW_Grid.tga",
        "W_Space_Reinforce_FOW_Grid.tga",
    };

    public static IList<string> HardcodedEawTextures { get; } = new List<string>
    {
        "splash.tga",
        "i_button_temporary.tga",
        "i_attention00.tga",
        "i_tree_arrow_right.tga",
        "load_overlay.tga",
        "i_pa_weather_sun.tga",
        "i_pa_weather_fire.tga",
        "i_pa_weather_snow.tga",
        "i_pa_weather_rain.tga",
        "i_pa_weather_wind.tga",
        "Menuback_Overlay.TGA",
        "i_button_space_station.tga",
        "i_button_ground_base.tga",
        "i_button_space_unitcount.tga",
        "i_button_ground_unitcount.tga",
        "i_dialogue_blank.tga",
        "checked_box.tga",
        "Galactic_Back.tga",
        "Generic_Space.tga",
        "Generic_Land.tga",
        "red_dot.tga",
        "yellow_dot.tga",
        "green_dot.tga",
        "i_tree_arrow_2right.tga",
        "i_tree_arrow_3right.tga",
        "i_tree_arrow_down.tga",
        "Generic_Flat_B.tga",
        "w_generic_white.tga",
        "w_shadow_blob.tga",
        "w_light_blob.tga",
        "p_particle_master.tga",
        "missing_texture_xxx.tga",
        "D_master_decal.tga",
        "p_particle_depth_master.tga",
        "MT_CommandBar.tga",
        "MT_CommandBarCompressed.dds",
        "DEFAULTPOINTER_00.TGA",
        "tractor_beam00.tga",
        "i_button_unknown.tga",
        "i_icon_stealth.tga",
        "e_line2.tga",
        "e_line.tga",
        "i_bar_icons_space.tga",
        "i_bar_icons_land.tga",
        "e_topbar2.tga",
        "e_topbar.tga",
        "e_against_frame.tga",
        "missing.tga",
        "i_encyclopedia_border.tga",
        "i_radar_default_blip.tga",
        "select_overlay.tga",
        "i_icon_raid.tga",
        "W_galaxy_line.tga",
        "W_galaxy_line_alpha.tga",
        "W_galaxy_dot.tga",
        "i_sa_defend_mode.tga",
        "i_sa_deploy.tga",
        "i_sa_interdict.tga",
        "i_sa_barrage_area.tga",
        "i_sa_capture_vehicles.tga",
        "i_sa_spread_out.tga",
        "i_sa_power_to_engines.tga",
        "i_sa_rocket_attack.tga",
        "i_sa_power_to_weapons.tga",
        "i_sa_tractor_beam.tga",
        "i_sa_fire_energy_weapon.tga",
        "i_sa_missile_jammer.tga",
        "i_sa_evasive_maneuvers.tga",
        "i_sa_all_ships_concentrate_fire.tga",
        "i_sa_sprint.tga",
        "i_sa_s_foil_mode.tga",
        "i_sa_maximum_firepower.tga",
        "i_sa_force_crush.tga",
        "i_sa_force_push.tga",
        "i_sa_force_lighting.tga",
        "i_sa_flame_thrower.tga",
        "i_sa_jetpack_jump.tga",
        "i_sa_force_protect.tga",
        "i_sa_hack_turret.tga",
        "i_sa_repair_vehicle.tga",
        "i_sa_sticky_bomb.tga",
        "i_sa_electronic_scramble.tga",
        "i_sa_area_heal.tga",
        "i_sa_join_me.tga",
        "i_sa_tow_cable_attack.tga",
        "i_sa_sensor_ping.tga",
        "i_sa_cover_me.tga",
        "i_sa_Harmonic_bomb.tga",
        "i_sa_drop_bomb.tga",
        "i_sa_weaken_enemy.tga",
        "i_sa_hunt.tga",
        "i_sa_lure.tga",
        "i_sa_self_destruct.tga",
        "i_sa_deploy_stormtroopers.tga",
        "i_sa_ion_cannon_shot.tga",
        "i_sa_lucky_shot.tga",
        "lightning_default.tga",
        "Mon_Mothma.tga",
        "Tarkin.tga",
        "W_Cable.tga",
        "i_information00.tga",
        "W_Laser_Pill.tga",
        "W_Space_FOW_Grid.tga",
        "W_Space_Reinforce_FOW_Grid.tga",
    };

    public static IList<string> GetHardcodedModelsAndParticles(GameEngineType engine)
    {
        return engine switch
        {
            GameEngineType.Eaw => HardcodedEawModelsParticles,
            GameEngineType.Foc => HardcodedFocModelsParticles,
            _ => throw new ArgumentOutOfRangeException(nameof(engine), engine, null)
        };
    }

    public static IList<string> GetHardcodedTextures(GameEngineType engine)
    {
        return engine switch
        {
            GameEngineType.Eaw => HardcodedEawTextures,
            GameEngineType.Foc => HardcodedFocTextures,
            _ => throw new ArgumentOutOfRangeException(nameof(engine), engine, null)
        };
    }
}