namespace PG.StarWarsGame.Engine.DataTypes;

public enum GameObjectType
{
    Unknown = 0,
    CinematicObject = 1,
    Container = 2,
    GenericHeroUnit = 3,
    GroundBase = 4,
    GroundBuildable = 5,
    GroundCompany = 6,
    GroundInfantry = 7,
    GroundStructure = 8,
    GroundVehicle = 9,
    HeroCompany = 10,
    HeroUnit = 11,
    IndigenousUnit = 12,
    LandBombingUnit = 13,
    LandPrimarySkydome = 14,
    LandSecondarySkydome = 15,
    Marker = 16,
    MiscObject = 17,
    MobileDefenseUnit = 18,
    MultiplayerStructureMarker = 19,
    Particle = 20,
    Planet = 21,
    Projectile = 22,
    Prop = 23,
    ScriptMarker = 24,
    SecondaryStructure = 25,
    SlaveCompany = 26,
    SlaveUnit = 27,
    SpaceBuildable = 28,
    SpacePrimarySkydome = 29,
    SpaceProp = 30,
    SpaceSecondarySkydome = 31,
    SpaceUnit = 32,
    SpecialEffect = 33,
    SpecialStructure = 34,
    Squadron = 35,
    StarBase = 36,
    TechBuilding = 37,
    TransportUnit = 38,
    UniqueUint = 39,
    UpgradeUnit = 40
}