using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace PG.StarWarsGame.Engine.Rendering.Animations;

public static class SupportedModelAnimationTypes
{
    public static IReadOnlyDictionary<ModelAnimationType, string> GetAnimationTypesForEngine(GameEngineType engineType)
    {
        return engineType switch
        {
            GameEngineType.Eaw => EawSupportedAnimations,
            GameEngineType.Foc => FocSupportedAnimations,
            _ => throw new NotSupportedException()
        };
    }

    [SuppressMessage("ReSharper", "StringLiteralTypo")]
    private static readonly Dictionary<ModelAnimationType, string> FocSupportedAnimations = new()
    {
        { FocModelAnimationTypes.Idle, "IDLE"},
        { FocModelAnimationTypes.SpaceIdle, "SPACE_IDLE"},
        { FocModelAnimationTypes.Move, "MOVE"},
        { FocModelAnimationTypes.TurnLeft, "TURNL"},
        { FocModelAnimationTypes.TurnRight, "TURNR"},
        { FocModelAnimationTypes.Attack, "ATTACK"},
        { FocModelAnimationTypes.AttackIdle, "ATTACKIDLE"},
        { FocModelAnimationTypes.Die, "DIE"},
        { FocModelAnimationTypes.Rotate, "ROTATE"},
        { FocModelAnimationTypes.SpecialA, "SPECIAL_A"},
        { FocModelAnimationTypes.SpecialB, "SPECIAL_B"},
        { FocModelAnimationTypes.SpecialC, "SPECIAL_C"},
        { FocModelAnimationTypes.TransitionToLeftTurn, "TURNL_BEGIN"},
        { FocModelAnimationTypes.TransitionFromLeftTurn, "TURNL_END"},
        { FocModelAnimationTypes.TransitionToRightTurn, "TURNR_BEGIN"},
        { FocModelAnimationTypes.TransitionFromRightTurn, "TURNR_END"},
        { FocModelAnimationTypes.TransitionToMove, "MOVESTART"},
        { FocModelAnimationTypes.TransitionFromMoveFrame0, "MOVE_ENDONE"},
        { FocModelAnimationTypes.TransitionFromMoveFrame40, "MOVE_ENDTWO"},
        { FocModelAnimationTypes.TransitionFromMoveFrame80, "MOVE_ENDTHREE"},
        { FocModelAnimationTypes.TransitionFromMoveFrame120, "MOVE_ENDFOUR"},
        { FocModelAnimationTypes.TurnLeftHalf, "TURNL_HALF"},
        { FocModelAnimationTypes.TurnLeftQuarter, "TURNL_QUARTER"},
        { FocModelAnimationTypes.TurnRightHalf, "TURNR_HALF"},
        { FocModelAnimationTypes.TurnRightQuarter, "TURNR_QUARTER"},
        { FocModelAnimationTypes.Deploy, "DEPLOY"},
        { FocModelAnimationTypes.Undeploy, "UNDEPLOY"},
        { FocModelAnimationTypes.Cinematic, "CINEMATIC"},
        { FocModelAnimationTypes.BlockBlaster, "BLOCK_BLASTER"},
        { FocModelAnimationTypes.RedirectBlaster, "REDIRECT_BLASTER"},
        { FocModelAnimationTypes.IdleBlockBlaster, "IDLE_BLOCKBLASTER"},
        { FocModelAnimationTypes.ForceWhirlwindAttack, "FW_ATTACK"},
        { FocModelAnimationTypes.ForceWhirlwindDie, "FW_DIE"},
        { FocModelAnimationTypes.ForceTelekinesisAttack, "FTK_ATTACK"},
        { FocModelAnimationTypes.ForceTelekinesisHold, "FTK_HOLD"},
        { FocModelAnimationTypes.ForceTelekinesisRelease, "FTK_RELEASE"},
        { FocModelAnimationTypes.ForceTelekinesisDie, "FTK_DIE"},
        { FocModelAnimationTypes.EarthquakeAttack, "FB_ATTACK"},
        { FocModelAnimationTypes.EarthquakeHold, "FB_HOLD"},
        { FocModelAnimationTypes.EarthquakeRelease, "FB_RELEASE"},
        { FocModelAnimationTypes.ForceLightningAttack, "FL_ATTACK"},
        { FocModelAnimationTypes.ForceLightningDie, "FL_DIE"},
        { FocModelAnimationTypes.ForceRun, "FORCE_RUN"},
        { FocModelAnimationTypes.TransportLanding, "LAND"},
        { FocModelAnimationTypes.TransportLeaving, "TAKEOFF"},
        { FocModelAnimationTypes.FlameAttack, "FLAME_ATTACK"},
        { FocModelAnimationTypes.Demolition, "DEMOLITION"},
        { FocModelAnimationTypes.BombToss, "BOMBTOSS"},
        { FocModelAnimationTypes.Jump, "JUMP"},
        { FocModelAnimationTypes.FlyIdle, "FLYIDLE"},
        { FocModelAnimationTypes.FlyLand, "FLYLAND"},
        { FocModelAnimationTypes.LandIdle, "FLYLANDIDLE"},
        { FocModelAnimationTypes.Land, "FLYLANDDROP"},
        { FocModelAnimationTypes.HcWin, "HC_WIN"},
        { FocModelAnimationTypes.HcLose, "HC_LOSE"},
        { FocModelAnimationTypes.HcDraw, "HC_DRAW"},
        { FocModelAnimationTypes.ShieldOn, "SHIELD_ON"},
        { FocModelAnimationTypes.ShieldOff, "SHIELD_OFF"},
        { FocModelAnimationTypes.CableAttackDie, "CA_DIE"},
        { FocModelAnimationTypes.DeployedCableAttackDie, "DEPLOYED_CA_DIE"},
        { FocModelAnimationTypes.DeployedDie, "DEPLOYED_DIE"},
        { FocModelAnimationTypes.RunAroundOnFire, "FIRE_MOVE"},
        { FocModelAnimationTypes.FireDie, "FIRE_DIE"},
        { FocModelAnimationTypes.PoundAttack, "POUND_ATTACK"},
        { FocModelAnimationTypes.EatAttack, "EAT_ATTACK"},
        { FocModelAnimationTypes.EatDie, "EATEN_DIE"},
        { FocModelAnimationTypes.MoveWalk, "WALKMOVE"},
        { FocModelAnimationTypes.MoveCrouch, "CROUCHMOVE"},
        { FocModelAnimationTypes.StructureOpen, "OPEN"},
        { FocModelAnimationTypes.StructureHold, "HOLD"},
        { FocModelAnimationTypes.StructureClose, "CLOSE"},
        { FocModelAnimationTypes.IdleCrouch, "CROUCHIDLE"},
        { FocModelAnimationTypes.TurnLeftCrouch, "CROUCHTURNL"},
        { FocModelAnimationTypes.TurnRightCrouch, "CROUCHTURNR"},
        { FocModelAnimationTypes.Build, "BUILD"},
        { FocModelAnimationTypes.TransitionOwnership, "TRANS"},
        { FocModelAnimationTypes.SelfDestruct, "SELF_DESTRUCT"},
        { FocModelAnimationTypes.Attention, "ATTENTION"},
        { FocModelAnimationTypes.Celebrate, "CELEBRATE"},
        { FocModelAnimationTypes.FlinchLeft, "FLINCHL"},
        { FocModelAnimationTypes.FlinchRight, "FLINCHR"},
        { FocModelAnimationTypes.FlinchFront, "FLINCHF"},
        { FocModelAnimationTypes.FlinchBack, "FLINCHB"},
        { FocModelAnimationTypes.AttackFlinchLeft, "ATTACKFLINCHL"},
        { FocModelAnimationTypes.AttackFlinchRight, "ATTACKFLINCHR"},
        { FocModelAnimationTypes.AttackFlinchFront, "ATTACKFLINCHF"},
        { FocModelAnimationTypes.AttackFlinchBack, "ATTACKFLINCHB"},
        { FocModelAnimationTypes.Talk, "TALK"},
        { FocModelAnimationTypes.TalkGesture, "TALKGESTURE"},
        { FocModelAnimationTypes.TalkQuestion, "TALKQUESTION"},
        { FocModelAnimationTypes.Hacking, "HACKING"},
        { FocModelAnimationTypes.Repairing, "REPAIRING"},
        { FocModelAnimationTypes.Choke, "CHOKE"},
        { FocModelAnimationTypes.ChokeDie, "CHOKEDEATH"},
        { FocModelAnimationTypes.DropTroopers, "TROOPDROP"},
        { FocModelAnimationTypes.RopeSlide, "ROPESLIDE"},
        { FocModelAnimationTypes.RopeLand, "ROPELAND"},
        { FocModelAnimationTypes.RopeDrop, "ROPE_DROP"},
        { FocModelAnimationTypes.RopeLift, "ROPE_LIFT"},
        { FocModelAnimationTypes.Alarm, "ALARM"},
        { FocModelAnimationTypes.Warning, "WARNING"},
        { FocModelAnimationTypes.Crushed, "CRUSHED"},
        { FocModelAnimationTypes.PowerDown, "POWERDOWN"},
        { FocModelAnimationTypes.PowerUp, "POWERUP"},
        { FocModelAnimationTypes.SpinMove, "SPINMOVE"},
        { FocModelAnimationTypes.ForceRevealBegin, "FORCE_REVEAL_BEGIN"},
        { FocModelAnimationTypes.ForceRevealLoop, "FORCE_REVEAL_LOOP"},
        { FocModelAnimationTypes.ForceRevealEnd, "FORCE_REVEAL_END"},
        { FocModelAnimationTypes.SaberThrow, "SWORD_THROW"},
        { FocModelAnimationTypes.SaberControl, "SWORD_CONTROL"},
        { FocModelAnimationTypes.SaberCatch, "SWORD_CATCH"},
        { FocModelAnimationTypes.SaberSpin, "SWORDSPIN"},
        { FocModelAnimationTypes.ContaminateAttack, "CONTAMINATE_ATTACK"},
        { FocModelAnimationTypes.ContaminateLoop, "CONTAMINATE_LOOP"},
        { FocModelAnimationTypes.ContaminateRelease, "CONTAMINATE_RELEASE"},
        { FocModelAnimationTypes.DeployedWalk, "WALK"},
        { FocModelAnimationTypes.PadBuild, "PAD_BUILD"},
        { FocModelAnimationTypes.PadSell, "PAD_SELL"},
        { FocModelAnimationTypes.Heal, "HEAL"},
    };

    [SuppressMessage("ReSharper", "StringLiteralTypo")]
    private static readonly Dictionary<ModelAnimationType, string> EawSupportedAnimations = new()
    {
        { EawModelAnimationTypes.Idle, "IDLE"},
        { EawModelAnimationTypes.SpaceIdle, "SPACE_IDLE"},
        { EawModelAnimationTypes.Move, "MOVE"},
        { EawModelAnimationTypes.TurnLeft, "TURNL"},
        { EawModelAnimationTypes.TurnRight, "TURNR"},
        { EawModelAnimationTypes.Attack, "ATTACK"},
        { EawModelAnimationTypes.AttackIdle, "ATTACKIDLE"},
        { EawModelAnimationTypes.Die, "DIE"},
        { EawModelAnimationTypes.Rotate, "ROTATE"},
        { EawModelAnimationTypes.SpecialA, "SPECIAL_A"},
        { EawModelAnimationTypes.SpecialB, "SPECIAL_B"},
        { EawModelAnimationTypes.SpecialC, "SPECIAL_C"},
        { EawModelAnimationTypes.TransitionToLeftTurn, "TURNL_BEGIN"},
        { EawModelAnimationTypes.TransitionFromLeftTurn, "TURNL_END"},
        { EawModelAnimationTypes.TransitionToRightTurn, "TURNR_BEGIN"},
        { EawModelAnimationTypes.TransitionFromRightTurn, "TURNR_END"},
        { EawModelAnimationTypes.TransitionToMove, "MOVESTART"},
        { EawModelAnimationTypes.TransitionFromMoveFrame0, "MOVE_ENDONE"},
        { EawModelAnimationTypes.TransitionFromMoveFrame40, "MOVE_ENDTWO"},
        { EawModelAnimationTypes.TransitionFromMoveFrame80, "MOVE_ENDTHREE"},
        { EawModelAnimationTypes.TransitionFromMoveFrame120, "MOVE_ENDFOUR"},
        { EawModelAnimationTypes.TurnLeftHalf, "TURNL_HALF"},
        { EawModelAnimationTypes.TurnLeftQuarter, "TURNL_QUARTER"},
        { EawModelAnimationTypes.TurnRightHalf, "TURNR_HALF"},
        { EawModelAnimationTypes.TurnRightQuarter, "TURNR_QUARTER"},
        { EawModelAnimationTypes.Deploy, "DEPLOY"},
        { EawModelAnimationTypes.Undeploy, "UNDEPLOY"},
        { EawModelAnimationTypes.Cinematic, "CINEMATIC"},
        { EawModelAnimationTypes.BlockBlaster, "BLOCK_BLASTER"},
        { EawModelAnimationTypes.RedirectBlaster, "REDIRECT_BLASTER"},
        { EawModelAnimationTypes.IdleBlockBlaster, "IDLE_BLOCKBLASTER"},
        { EawModelAnimationTypes.ForceWhirlwindAttack, "FW_ATTACK"},
        { EawModelAnimationTypes.ForceWhirlwindDie, "FW_DIE"},
        { EawModelAnimationTypes.ForceTelekinesisAttack, "FTK_ATTACK"},
        { EawModelAnimationTypes.ForceTelekinesisHold, "FTK_HOLD"},
        { EawModelAnimationTypes.ForceTelekinesisRelease, "FTK_RELEASE"},
        { EawModelAnimationTypes.ForceTelekinesisDie, "FTK_DIE"},
        { EawModelAnimationTypes.EarthquakeAttack, "FB_ATTACK"},
        { EawModelAnimationTypes.EarthquakeHold, "FB_HOLD"},
        { EawModelAnimationTypes.EarthquakeRelease, "FB_RELEASE"},
        { EawModelAnimationTypes.ForceLightningAttack, "FL_ATTACK"},
        { EawModelAnimationTypes.ForceLightningDie, "FL_DIE"},
        { EawModelAnimationTypes.ForceRun, "FORCE_RUN"},
        { EawModelAnimationTypes.TransportLanding, "LAND"},
        { EawModelAnimationTypes.TransportLeaving, "TAKEOFF"},
        { EawModelAnimationTypes.FlameAttack, "FLAME_ATTACK"},
        { EawModelAnimationTypes.Demolition, "DEMOLITION"},
        { EawModelAnimationTypes.BombToss, "BOMBTOSS"},
        { EawModelAnimationTypes.Jump, "JUMP"},
        { EawModelAnimationTypes.FlyIdle, "FLYIDLE"},
        { EawModelAnimationTypes.FlyLand, "FLYLAND"},
        { EawModelAnimationTypes.LandIdle, "FLYLANDIDLE"},
        { EawModelAnimationTypes.Land, "FLYLANDDROP"},
        { EawModelAnimationTypes.HcWin, "HC_WIN"},
        { EawModelAnimationTypes.HcLose, "HC_LOSE"},
        { EawModelAnimationTypes.HcDraw, "HC_DRAW"},
        { EawModelAnimationTypes.ShieldOn, "SHIELD_ON"},
        { EawModelAnimationTypes.ShieldOff, "SHIELD_OFF"},
        { EawModelAnimationTypes.CableAttackDie, "CA_DIE"},
        { EawModelAnimationTypes.DeployedCableAttackDie, "DEPLOYED_CA_DIE"},
        { EawModelAnimationTypes.DeployedDie, "DEPLOYED_DIE"},
        { EawModelAnimationTypes.RunAroundOnFire, "FIRE_MOVE"},
        { EawModelAnimationTypes.FireDie, "FIRE_DIE"},
        { EawModelAnimationTypes.PoundAttack, "POUND_ATTACK"},
        { EawModelAnimationTypes.EatAttack, "EAT_ATTACK"},
        { EawModelAnimationTypes.EatDie, "EATEN_DIE"},
        { EawModelAnimationTypes.MoveWalk, "WALKMOVE"},
        { EawModelAnimationTypes.MoveCrouch, "CROUCHMOVE"},
        { EawModelAnimationTypes.StructureOpen, "OPEN"},
        { EawModelAnimationTypes.StructureHold, "HOLD"},
        { EawModelAnimationTypes.StructureClose, "CLOSE"},
        { EawModelAnimationTypes.IdleCrouch, "CROUCHIDLE"},
        { EawModelAnimationTypes.TurnLeftCrouch, "CROUCHTURNL"},
        { EawModelAnimationTypes.TurnRightCrouch, "CROUCHTURNR"},
        { EawModelAnimationTypes.Build, "BUILD"},
        { EawModelAnimationTypes.TransitionOwnership, "TRANS"},
        { EawModelAnimationTypes.SelfDestruct, "SELF_DESTRUCT"},
        { EawModelAnimationTypes.Attention, "ATTENTION"},
        { EawModelAnimationTypes.Celebrate, "CELEBRATE"},
        { EawModelAnimationTypes.FlinchLeft, "FLINCHL"},
        { EawModelAnimationTypes.FlinchRight, "FLINCHR"},
        { EawModelAnimationTypes.FlinchFront, "FLINCHF"},
        { EawModelAnimationTypes.FlinchBack, "FLINCHB"},
        { EawModelAnimationTypes.AttackFlinchLeft, "ATTACKFLINCHL"},
        { EawModelAnimationTypes.AttackFlinchRight, "ATTACKFLINCHR"},
        { EawModelAnimationTypes.AttackFlinchFront, "ATTACKFLINCHF"},
        { EawModelAnimationTypes.AttackFlinchBack, "ATTACKFLINCHB"},
        { EawModelAnimationTypes.Talk, "TALK"},
        { EawModelAnimationTypes.TalkGesture, "TALKGESTURE"},
        { EawModelAnimationTypes.TalkQuestion, "TALKQUESTION"},
        { EawModelAnimationTypes.Hacking, "HACKING"},
        { EawModelAnimationTypes.Repairing, "REPAIRING"},
        { EawModelAnimationTypes.Choke, "CHOKE"},
        { EawModelAnimationTypes.ChokeDie, "CHOKEDEATH"},
        { EawModelAnimationTypes.DropTroopers, "TROOPDROP"},
        { EawModelAnimationTypes.RopeSlide, "ROPESLIDE"},
        { EawModelAnimationTypes.RopeLand, "ROPELAND"},
        { EawModelAnimationTypes.RopeDrop, "ROPE_DROP"},
        { EawModelAnimationTypes.RopeLift, "ROPE_LIFT"},
        { EawModelAnimationTypes.Alarm, "ALARM"},
        { EawModelAnimationTypes.Warning, "WARNING"},
        { EawModelAnimationTypes.Crushed, "CRUSHED"},
        { EawModelAnimationTypes.PowerDown, "POWERDOWN"},
        { EawModelAnimationTypes.PowerUp, "POWERUP"}
    };
}